"""
Phase 4 tuning knobs - simulated LiDAR tunnel-shape comparison (T1 vs T2).

No external data. Both "scans" are generated by this script.
"""

import numpy as np

# --- tunnel cross-section (the baseline / T1 shape) ---------------------
N_POINTS = 360                 # samples around the outline (one per degree)
BASE_RADIUS = 2.6             # m, nominal half-size of the drift
ROOF_RISE = 0.12              # taller crown  (fraction of BASE_RADIUS)
WALL_PINCH = 0.06             # slight side pinch (fraction), gives a D / arch shape
SCAN_NOISE_M = 0.012          # per-point LiDAR range noise (std dev, m), added to both scans

# --- deformation injected into the later scan (T2) --------------------
DEV_THRESHOLD_M = 0.10        # flag any smoothed inward movement bigger than this (m)
DEFORM_DEPTH_RANGE = (0.04, 0.22)   # random inward depth per regenerate (m)
DEFORM_WIDTH_RANGE = (0.30, 0.60)   # random angular half-width of the sag (radians)
SAFE_SCAN_PROBABILITY = 0.30 # chance a regenerate produces only noise (no real sag)
DEPTH_SCALE = 1.0            # global multiplier on the sag depth, live keys [ and ]

# Where sags are allowed to appear, and how likely each is (roof-weighted).
DEFORM_REGIONS = {           # name -> (centre angle in degrees, weight)
    "roof (crown)": (90, 0.55),
    "left wall": (180, 0.15),
    "right wall": (0, 0.15),
    "floor (heave)": (270, 0.15),
}

SMOOTH_WINDOW = 7            # circular moving-average window for the deviation curve

# --- display ---------------------------------------------------------
WINDOW_TITLE = "AI Analysis Engine - Structural Shape-Tracking (Phase 4)"
ALERT_TEXT = "ROOF SAG / NARROWING DETECTED"
OK_TEXT = "STRUCTURE WITHIN TOLERANCE"
SIM_CAPTION = ("SIMULATED SCAN COMPARISON  -  stand-in for the rover's LiDAR "
               "(not yet integrated).  The T1-vs-T2 deviation logic is real.")
SHOW_WHISKERS = True         # radial lines between matching T1/T2 points in the flagged zone
